substitutions:
  is480x320: false
  name: "touch-display-gregs-office"
  friendly_name: "Touch Display - Greg's Office"
  font1: "montserrat_12" #"montserrat_14"
  font2: "montserrat_14" #"montserrat_18"
  font3: "montserrat_16" #"montserrat_30"
  font4: "montserrat_18" #"montserrat_24"
  font4b: "montserrat_24" 
  font4a: "montserrat_34" #""montserrat_60"
  font4c: "montserrat_30"
  font5: "montserrat_40" #"montserrat_60"

  media_player_entity: "media_player.mainfloor_pi"
  



packages:   # as a list
- !include common/CYD-2432S028R.yaml
- !include common/common_elements.yaml
- !include common/sensors.yaml
- !include common/lvgl_stuff.yaml

   

