substitutions:
  display_width: 320
  display_height: 240

esp32:
  board: esp32dev
  framework:
    type: esp-idf

spi:
  - id: lcd
    clk_pin: GPIO14
    mosi_pin: GPIO13
    miso_pin: GPIO12
  - id: touch
    clk_pin: GPIO25
    mosi_pin: GPIO32
    miso_pin: GPIO39

touchscreen:
  platform: xpt2046
  spi_id: touch
  cs_pin: 33
  # interrupt_pin: 36
  update_interval: 50ms
  #threshold: 400
  calibration:
    x_min: 280
    x_max: 3860
    y_min: 340
    y_max: 3860
  transform:
    mirror_x: false
    mirror_y: false
    swap_xy: true

# Define pins for backlight display and back LED1
output:
  - platform: ledc
    pin: GPIO21
    id: backlight
  - platform: ledc
    id: output_red
    pin: GPIO4
    inverted: true
  - platform: ledc
    id: output_green
    pin: GPIO16
    inverted: true
  - platform: ledc
    id: output_blue
    pin: GPIO17
    inverted: true

display:
  - platform: ili9xxx
    model: ILI9341
    spi_id: lcd
    cs_pin: 15
    dc_pin: 2
    id: my_display
    rotation: 90
    color_palette: 8BIT
    data_rate: 40MHz
    invert_colors: false    
    dimensions: 240x320
    auto_clear_enabled: false
    update_interval: never

# Define a monochromatic, dimmable light for the backlight
light:
  - id: rgbLed
    platform: rgb
    name: "RGB LED"
    red: output_red
    green: output_green
    blue: output_blue
    restore_mode: ALWAYS_OFF
    default_transition_length: 2s   